swagger: "2.0"
info:
  version: "0.0.1"
  title: Syba-Backend
# during dev, should point to your local machine
host: localhost:7000
# basePath prefixes all resource paths 
basePath: /api
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /swagger:
    x-swagger-pipe: swagger_raw
  /batchconfigs:
    x-swagger-router-controller: batches
    get: 
      description: Returns all known batches
      parameters: 
        - name: filter
          in: query
          description: Where clause to get only certain batches
          required: false
          type: string
      responses:
        "200":
          description: Success
          schema:
            type: array
            items: 
              # a pointer to a definition
              $ref: "#/definitions/Batchconfig"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    post:
      description: posts a new batchconfig
      parameters: 
        - name: batch
          in: body
          description: the batchconfig to store
          required: true
          schema: 
            $ref: "#/definitions/Batchconfig"
      responses:
        "200":
          description: Success
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /batchconfigs/{BOID}:
    x-swagger-router-controller: batches
    get:
      description: Returns one Batchconfig by id including the statistical Kennzahl information
      operationId: getById
      parameters:
        - name: BOID
          in: path
          description: boid of batch to fetch
          required: true
          type: string
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/Batchconfig"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    put: 
      description: Updates a Batchconfig
      parameters:
        - name: BOID
          in: path
          description: boid of batch to fetch
          required: true
          type: string
        - name: batchconfig
          in: body
          description: the payload data
          required: true
          schema: 
            $ref: "#/definitions/Batchconfig"
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/Batchconfig"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    delete:
      description: Removes a Batchconfig and all its associated data
      parameters:
        - name: BOID
          in: path
          description: boid of batch to fetch
          required: true
          type: string
      responses:
              "200":
                description: Success
                schema:
                  $ref: "#/definitions/Batchconfig"
              default:
                description: Error
                schema:
                  $ref: "#/definitions/ErrorResponse"
  /batchconfigs/{BOID}/reload:
    x-swagger-router-controller: batches
    post:
      description: Reloads a batchconfig completly, recalculates all runs and all kennzahlen
      operationId: reloadBatchConfig
      parameters:
        - name: BOID
          in: path
          description: BOID der Batchconfig, die reloaded werden soll
          required: true
          type: string
      responses:
        "200":
          description: Success
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /batchconfigs/{ITSBATCHCONFIG}/kennzahlvalues/{ITSKENNZAHLCONFIG}:
    x-swagger-router-controller: kennzahlvalues
    get: 
      description: Returns a kennzahl history for one batchconfig/kennzahlconfig
      operationId: getKennzahlWithHistory
      parameters: 
        - name: ITSBATCHCONFIG
          in: path
          description: boid of batchconfig to fetch KennzahlValues for
          required: true
          type: string
        - name: ITSKENNZAHLCONFIG
          in: path
          description: boid of kennzahlConfig to fetch KennzahlValues for
          required: true
          type: string
      responses:
        "200":
          description: Success
          schema:
            type: array
            items: 
              # a pointer to a definition
              $ref: "#/definitions/KennzahlValue"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /batchconfigs/{itsBatchConfig}/run/{itsBatchRun}/kennzahlen:
    x-swagger-router-controller: kennzahlvalues
    get:
      description: Returns all kennzahlValues for a batchconfig
      operationId: getKennzahlenForRun
      parameters:
        - name: itsBatchConfig
          in: path
          description: boid of batchconfig to fetch KennzahlValues for
          required: true
          type: string
        - name: itsBatchRun
          in: path
          description: boid of batchconfig to fetch KennzahlValues for
          required: true
          type: string
      responses:
        "200":
          description: Success
          schema:
            type: array
            items:
              # a pointer to a definition
              $ref: "#/definitions/RunKennzahl"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"

  /batchruns:
    x-swagger-router-controller: batchruns
    get: 
      description: Returns all known runs
      parameters: 
        - name: filter
          in: query
          description: Where clause to get only certain batches
          required: false
          type: string
        - name: ITSBATCHCONFIG
          in: query
          description: the boid of the batch to return the runs for
          required: true
          type: string
      responses:
        "200":
          description: Success
          schema:
            type: array
            items: 
              # a pointer to a definition
              $ref: "#/definitions/Run"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /batchruns/{BOID}:
    x-swagger-router-controller: batchruns
    get:
      description: Returns one Batchrun by id
      operationId: getById
      parameters:
        - name: BOID
          in: path
          description: boid of batch to fetch
          required: true
          type: string
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/Run"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    put: 
      description: Updates a Batchrun
      parameters:
        - name: BOID
          in: path
          description: boid of batch to fetch
          required: true
          type: string
        - name: batchrun
          in: body
          description: the payload data
          required: true
          schema: 
            $ref: "#/definitions/Run"
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/Batchconfig"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /syriusbatches:
    x-swagger-router-controller: syriusbatches
    get:
      description: Returns all known SyriusBatches
      parameters:
        - name: filter
          in: query
          description: Where clause to get only certain batches
          required: false
          type: string
      responses:
        "200":
          description: Success
          schema:
            type: array
            items:
              # a pointer to a definition
              $ref: "#/definitions/SyriusBatch"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"

  /users:
    x-swagger-router-controller: batches
    get: 
      description: Returns all known users
      responses:
        "200":
          description: Success
          schema:
            type: array
            items: 
              # a pointer to a definition
              $ref: "#/definitions/User"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /kennzahlen:
    x-swagger-router-controller: kennzahlen
    get:
      description: Returns all known kennzahlen
      responses:
        "200":
          description: Success
          schema:
            type: array
            items:
              # a pointer to a definition
              $ref: "#/definitions/User"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /kennzahlconfigs:
    x-swagger-router-controller: kennzahlconfigs
    get:
      description: Returns all known kennzahlen
      responses:
        "200":
          description: Success
          schema:
            type: array
            items:
              # a pointer to a definition
              $ref: "#/definitions/User"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"

# complex objects have schema definitions
definitions:
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
  Batchconfig:
    type: object
    required:
      - boid
      - name
      - description
      - itsSyriusBatch
    properties:
      boid:
        type: string
      itsSyriusBatch:
        type: string
      name: 
        type: string
      description: 
        type: string
      active:
        type: integer
  SyriusBatch:
    type: object
    required:
      - boid
      - name
      - description
      - itsSyriusBatch
    properties:
      boid:
        type: string
      itsSyriusBatch:
        type: string
      name:
        type: string
      description:
        type: string
      active:
        type: integer
  Run:
    type: object
    required: 
      - boid
    properties: 
      boid:
        type: string
      itsBatchconfig:
        type: string
      itsSyriusBatch:
        type: string
      itsSyriusBatchLauf:
        type: string
      started:
        type: string
        format: date-time
      ended: 
        type: string
        format: date-time
      comment:
        type: string
  KennzahlValue:
    type: object
    properties:
      boid:
        type: string
      itsBatchRun:
        type: string
      itsKennzahlConfig:
        type: string
      itsBatchconfig:
        type: string
      itsSyriusBatch:
        type: string
      numbervalue:
        type: string
      timestampValue:
        type: string
        format: date-time
  RunKennzahl:
    type: object
    properties:
      ITSBATCHRUN:
        type: string
      ITSKENNZAHLCONFIG:
        type: string
      ITSBATCHCONFIG:
        type: string
      ITSKENNZAHL:
        type: string
      NAME:
        type: string
      VALUE:
        type: string
      AVG:
        type: string
      STDDEV:
        type: string
      MIN:
        type: string
      MAX:
        type: string

  User:
    type: object
    required: 
      - id
    properties:
      firstname: 
        type: string
      lastname: 
        type: string
      id: 
        type: string
        
